<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDependencyFile>true</GenerateDependencyFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PathMap>$(MSBuildProjectDirectory)=IMGUI/</PathMap>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)UserProperties.xml"
          Condition="Exists('$(MSBuildThisFileDirectory)UserProperties.xml')" />

  <Target Name="VerifyModReferences" BeforeTargets="Build">
    <Error Text="You forgot to configure UserProperties.xml"
           Condition="!Exists('$(MSBuildThisFileDirectory)UserProperties.xml')" />
  </Target>

  <Target Name="PrepareMod" AfterTargets="Build">
    <PropertyGroup>
      <ModCompileOutputDir Condition="'$(ModOutputDir)' != ''">$(ModOutputDir)</ModCompileOutputDir>
      <ModCompileOutputDir Condition="'$(ModOutputDir)' == ''">$(ProjectDir)out</ModCompileOutputDir>
    </PropertyGroup>

    <ItemGroup>
      <ModFiles Include="$(TargetDir)$(TargetName).dll;$(TargetDir)$(TargetName).pdb;$(TargetDir)$(TargetName).deps.json;$(TargetDir)ImGui.NET.dll;$(ProjectDir)Metadata.xml;$(ProjectDir)LICENSE"/>
      <NativeAssets Include="$(NuGetPackageRoot)imgui.net\1.90.9.1\runtimes\**\native\*"/>
    </ItemGroup>
    
    <MakeDir Directories="$(ModCompileOutputDir)"/>
    <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModCompileOutputDir)"/>
    <Copy SourceFiles="@(NativeAssets)" DestinationFolder="$(ModCompileOutputDir)\runtimes\%(RecursiveDir)"/>
  </Target>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.90.9.1"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Common">
      <HintPath>$(FezDir)\Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ContentSerialization">
      <HintPath>$(FezDir)\ContentSerialization.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="EasyStorage">
      <HintPath>$(FezDir)\EasyStorage.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FEZ">
      <HintPath>$(FezDir)\HAT.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FezEngine">
      <HintPath>$(FezDir)\FezEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FNA">
      <HintPath>$(FezDir)\FNA.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="XnaWordWrapCore">
      <HintPath>$(FezDir)\XnaWordWrapCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$(MonoModDir)\MonoMod.RuntimeDetour.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(MonoModDir)\MonoMod.Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(MonoModDir)\Mono.Cecil.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
